### ISSUE TITLE
Deposit functionality

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#13]
The current deposit functionality needs some work before it's ready for complex applications. Below are my proposed changes & additions to the deposit API

### Deposit
3 deposit methods for Wallet, each of which returns a tx hash as soon as they're broadcast
- `.depositEth(currency, amount, options)`
- `.initiateTokenDeposit(currency, amount, options)`
- `.completeTokenDeposit(txId, options)`

The `options` param would allow the user to customize things like gas price / gas limit

### Get pending deposits
- A method is required to get a wallet's pending deposits. This will be called once when the wallet is loaded, and is required to keep state up to date if the user does something like close the app or lose connection half way through a deposit
A pending deposit would need have a type `eth` or `token`. the `token` type could be
- `initiated` and `unconfirmed` (`approve` tx unconfirmed)
- `initiated` and `confirmed` (`approve` tx mined)
- `completing` (`deposit` tx mined)
Rough example of what the `.getPendingDeposits()` return value could look like:
```
[
  {
     type: "eth",
     amount: "..."
     txId: "..."
     timeBroadcast: "..."
  },
  {
     type: "token",
     stage: "initiated",
     confirmed: bool,
     currency: "...",
     amount: "...",
     txId: "...",
     timeBroadcast: "..."
  },
  {
     type: "token",
     stage: "completing",
     currency: "...",
     amount: "...",
     txId: "...",
     timeBroadcast: "..."
  }
]
```

### Deposit event API
- We need an event API to notify the front-end when a deposit has changed status. The event API would need to be aware of deposits that were initiated outside of the SDK. The message passed with an event would be similar to that of an object returned part of the `.getPendingDeposits()` method

**Comment by morfj** [comment]
Any work remaining here?
