### ISSUE TITLE
Annoying console logs

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#16]
Currently, this lib logs to the console as it runs without an apparent way to disable it. 

I suggest that when things appear to be running as expected, logs aren't shown. In unusual circumstances like an error, I think it's fine to show a log.

Please advise @morfj

**Comment by morfj** [comment]
It isnt supposed to log to the console so if it is, thats a bug. 
It should only log to console if `LOGLEVEL=debug` (and then only to stderr)
What messages are you seeing?

**Comment by liamaharon** [comment]
You're right, looks like it only uses console.log in one file:
`nahmii-provider.js` ln 63, 70, 75.

Should these be changed to `dbg(...)`?

**Comment by morfj** [comment]
Yes, those should be changed to dbg() calls instead.  #copypastefailure

**Comment by morfj** [comment]
Should be fixed in beta11
