### ISSUE TITLE
Requests using a token generated by the identity server often fail with code 503

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#17]
The requests fail for a few minutes, seem OK for ~15 seconds, then go back to failing

503 response request and response headers:
![screenshot from 2018-10-01 13-26-46](https://user-images.githubusercontent.com/16665596/46268436-c4e92e00-c57d-11e8-9e81-cc2fb07f7fb0.png)

Notice that almost immediately after this, with the exact same token, the requests start to return 200
![screenshot from 2018-10-01 13-27-05](https://user-images.githubusercontent.com/16665596/46268467-e0543900-c57d-11e8-9729-05bb341324e2.png)

A short time later, the requests go back to failing.

The response doesn't seem to give any clues as to why it's failing, only a generic 503 page:
```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by morfj** [comment]
Ill look into it. 503s are typically due to a reverse proxy / loadbalancer issue!

**Comment by morfj** [comment]
This is not a bug in the SDK itself, but rather an issue with the deployed service.
