### ISSUE TITLE
Consider using the hubii eslint config, or a variation of it

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#21]
Having a defined set of code style standards will become more important the contributors count increases.

@jonbern had the initiative to create a company-wide config some months ago, I think it would be beneficial to put it into action in this repo https://github.com/hubiinetwork/eslint-config

As well as making it easy to enforce code quality standards, defining an eslint config can increase development efficiency in a lot of editors that automatically do things like indentation, string definition rules, spacing rules, etc for you (srsly, who wants to spend their time doing that stuff... :smile:)

**Comment by morfj** [comment]
We cant use it in a public repo since the base config is in a private one!

**Comment by liamaharon** [comment]
Maybe we could make the base config repo public, or use one of the other many publically available ones?
