### ISSUE TITLE
utils.isSignedBy doesn't seem to be recognising a valid signature

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#26]
Came across this issue when trying to use the airdriip-service, which uses the SDK's `isSignedBy` function.

Payload sent to the airdriip service:
```json
{
  "document": "I agree to the nahmii airdriip T&C and wish to register my address",
  "sender": "0x910c4BA923B2243dc13e00A066eEfb8ffd905EB0",
  "seal": {
    "hash": "0x01d2d0f6d4d8584977c45f770815d1db3c67475c28419838549ce7c4626b44c1",
    "signature": {
      "v": 27,
      "r": "0xd22cd2712c47c404d436e0e6075ffe4d617f457261ba02386bb132a999a6d467",
      "s": "0x111410a4e46fd825a5a686b20dd385811932e6956e3684baf13ba94d4cc31069"
    }
  }
}
```

Response:
`422: Signature is not matching.`

---

Converting the signature into RPC format, we can verify it's correct:
```js
import { toRpcSig, toBuffer } from 'ethereumjs-util';

const sig = {
  v: 27,
  r: "0xd22cd2712c47c404d436e0e6075ffe4d617f457261ba02386bb132a999a6d467",
  s: "0x111410a4e46fd825a5a686b20dd385811932e6956e3684baf13ba94d4cc31069"
}
const rpcSig = toRpcSig(sig.v, toBuffer(sig.r), toBuffer(sig.s));
console.log(rpcSig);
```
>0x0946d84a81606a20271f5a7ce8f3e9156e8c9b2e5eed56954fb3a2a6632f5022388eb4ba2dbf3ff0bfb46ad40efbe42f93feee242ae2e55a016d1fcc770deddd01

Etherscan verifying the signature is valid: https://etherscan.io/verifySig/1380
ethers.js (v4.0.0 or greater required) verifying the signature is valid:
```js
const ethers = require('ethers');

const signature = '0x0946d84a81606a20271f5a7ce8f3e9156e8c9b2e5eed56954fb3a2a6632f5022388eb4ba2dbf3ff0bfb46ad40efbe42f93feee242ae2e55a016d1fcc770deddd01';
const message = '0x9daff1073bc37bd6d0261e48bda49f3ba1bbbd71838a34602acb06407aa5ea47';

console.log(ethers.utils.verifyMessage(message, signature));
```
>0x910c4BA923B2243dc13e00A066eEfb8ffd905EB0

---

I've tested this using
- the ethers.js `Wallet.prototype.signMessage` function
- the Ledger Nano S `eth.signPersonalMessage` function
- the Trezor `Session.signEthMessage` function

and had the same results

**Comment by liamaharon** [comment]
The ethers `verifyMessage` implementation may come in useful fixing this:
https://github.com/ethers-io/ethers.js/blob/fa68385cfefdc725b4233083e5ba681b8319d78a/src.ts/utils/secp256k1.ts#L107

**Comment by morfj** [comment]
You should sign it using the SDK functions. The sign() and isSignedBy() are symetrical.

**Comment by liamaharon** [comment]
Update:

I've looked into this, and the problem appears to be that internally, both the ethersjs library, Ledger Nano S, and Trezor sign messages like this:
```js
function getHash(message) {
  const payload = ethers.utils.concat([
    toUtf8Bytes('\x19Ethereum Signed Message:\n'),
    toUtf8Bytes(String(message.length)),
        ((typeof (message) === 'string') ? toUtf8Bytes(message) : message),
  ]);
  return keccak256(payload);
}

signMessage(message) {
  return this.signDigest(getHash(message));
}
```

I'm running into an issue, where the nahmii-sdk `util.ethHash` function is returning a different value than the `getHash` function I've described above. My best guess at why this is happening is because in `getHash`, the arguments are converted into a type `uint8` byte array while in the nahmii-sdk `ethHash` function the arguments are some other type?

For example
```js
const messageHash = nahmii.utils.hash(MESSAGE);
const ledgerSig = await ledgerSignMessage(messageHash); // could swap out for Trezor sign or an ethers wallet sign
const nahmiiSig = await nahmii.utils.sign(messageHash, PRIVATE_KEY);

nahmii.utils.recoverAddress(getHash(messageHash), ledgerSig); // correct address
nahmii.utils.recoverAddress(nahmii.utils.ethHash(messageHash), ledgerSig); // wrong address

nahmii.utils.recoverAddress(getHash(messageHash), nahmiiSig); // wrong address
nahmii.utils.recoverAddress(nahmii.utils.ethHash(messageHash), nahmiiSig); // correct address
```

This means that the `nahmii.utils.isSignedBy` function is unable to verify a signature signed by a Ledger or Trezor at the moment.

I've pinged @jijordre about this and will try working through this with him.

**Comment by liamaharon** [comment]
Oh boy. 
Turns out there was no problem with the SDK. 
My confusion stemmed from a combination of:
1. The airdriip service using an outdated SDK version, which didn't hash correctly (PR to fix this: https://github.com/hubiinetwork/airdriip-service/pull/2)
2. Unknowingly changing SDK versions when switching my SDK source from my local node_modules to a local git repo
2. Only correctly using `ethers.utils.arrayify(messageHash)` once I'd already (accidentally) switched to an incompatible SDK version.

Thanks @jijordre for helping put me on the right track with the repository proving the latest version of the SDK is aligned with the ethers library. Would probably still be chasing my own tail without that example :relieved:
