### ISSUE TITLE
Refactor and support v1.0-ropsten.8

### ISSUE THREAD

**Issue by katat** [hubiinetwork/nahmii-sdk#39]
Refactor based on the data structure changes in https://github.com/hubiinetwork/nahmii-contracts/releases/tag/v1.0-ropsten.6

- [x] Support Null Settlement
- [x] Refactor `getCurrentPaymentChallenge` into different functions for checking the challenge statuses. These functions will wrap the contract functions of `proposalNonce`, `proposalExpirationTime`, `hasProposalExpired`, `proposalStageAmount`, `proposalStatus`
- [x] Refactor `depositTokens` to use `receiveTokens` which has an added argument `balanceType`
- [x] Update abis

**Comment by liamaharon** [comment]
@katat should we update this issue to support v1.0-ropsten.7 instead?

**Comment by katat** [comment]
@liamaharon Yes, I will continue the refactor on the branch https://github.com/hubiinetwork/nahmii-sdk/pull/40
