### ISSUE TITLE
Create tests for non-nahmii specific Wallet functionality

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-sdk#50]
- [x] getAddress method
- [x] getBalance method
- [x] getTransactionCount method
- [x] sendTransaction method 
- [x] sign method
- [x] signMessage method

eg tests should fail if signingKey isn't added to a Wallet instance created from a private key

**Comment by morfj** [comment]
Adding some tests that can show how signing is supposed to be done (with a SW wallet) can also add as documentation/example for people on how to use the class.
