### ISSUE TITLE
Payment.from() and Receipt.from() breaking change due to requiring wallet instance

### ISSUE THREAD

**Issue by jonbern** [hubiinetwork/nahmii-sdk#51]
Previously it was possible to instantiate a Payment object without a real provider or a wallet instance through the `from()` function:

```JavaScript
const payment = sdk.Payment.from(json);
return payment.isSigned();
```

Now this is not possible anymore, and I need to pass a `Wallet` instance to the `from()` function. This breaks functionality in Trading AP that is used to check whether Payments and Receipts are signed.

To get around this, I have to write this sort of hacky code: 

```JavaScript
const config = require('./config');

const dummyProvider = {
  network: {
    chainId: '3'
  },
  resolveName: () => Promise.resolve('Ropsten'),
  operatorAddress: config.ethereum.contractOwner
};

// A random private key (Trading API doesn't sign anything, it just needs to check if something already has been signed)
const dummyPrivateKey = '0x010f3fa2b24726878516342f463f3ff36105ad51325201179deafdc38357a319';

const dummyWallet = new sdk.Wallet(dummyPrivateKey, dummyProvider);

const payment = sdk.Payment.from(dummyWallet, json);
return payment.isSigned();
```

I think it's an unintentional consequence that Wallet now has become required in order to check the signature.

**Comment by morfj** [comment]
I think it should be quite possible to instantiate the Payment or Receipt classes by giving `null` as the wallet. The wallet is only needed if you are to sign an object.

**Comment by jonbern** [comment]
I know that's the intention, but currently it doesn't work that way. When I send `null` instead of an instance of `Wallet` I get:

```JavaScript
TypeError: Cannot read property 'provider' of null
      at new Payment (/Users/jon/Code/hubii/nahmii-sdk/lib/payment.js:56:32)
      at Function.from (/Users/jon/Code/hubii/nahmii-sdk/lib/payment.js:162:19)
```

The problem lies here: https://github.com/hubiinetwork/nahmii-sdk/blob/7efe1f8cce3d5ca41d195c16319539210480898d/lib/payment.js#L58

**Comment by liamaharon** [comment]
I'll look into this today
