### ISSUE TITLE
Silent failure-and-continue

### ISSUE THREAD

**Issue by morfj** [hubiinetwork/nahmii-sdk#65]
Swallowing error such as these can potentially lead to a disaster by allowing the function to keep running without handling the error. As a **minimum** the error should be debug logged. If its actually NOT an error, then the design should be reconsidered as it is using errors for something it shouldnt.

https://github.com/hubiinetwork/nahmii-sdk/blob/842d8cc97fe5717101b4b3ec256d25d8d355f612/lib/settlement.js#L56

**Comment by katat** [comment]
Thanks. I will refactor the codes for this issue as well as #60 today.
