### ISSUE TITLE
Enhance the message for minimum balance errors

### ISSUE THREAD

**Issue by katat** [hubiinetwork/nahmii-sdk#81]
The backend API can response the reason of this error in the format:
```
{"message":"Insufficient funds: The minimum balance of this token is 0.01.","stack":"..."}
```

But the SDK only says `Insufficient funds!`

https://github.com/hubiinetwork/nahmii-sdk/blob/0d9e9210ef6dcc8d1c00488953f2f8cbe8f6f0e5/lib/nahmii-provider.js#L189

The downstream clients, such as the hubii-core, need to know the requirement for the minimum balance in order to show a detailed error message. Also, the front end clients need to localize the message, so it'd better provide a way for the clients to know the type of error and the required minimum balance.

Here is a suggestion:

1. Create a new error class called `InsufficientFundError` that extends the Error class. This error adds a new field called `minimumBalance`.

2. Parse the `0.01` from the `message` field of the API error response, and save it to the `minimumBalance` of a `InsufficientFundError` instance. (It would be better and safer if the API can return an additional field for the minimum balance, so the SDK won't need to do the parsing.)

**Comment by morfj** [comment]
Should be implemented in PR #82
